# Generated by Django 3.2.3 on 2021-09-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App1',
            new_name='Create',
        ),
    ]
