# Generated by Django 3.2.3 on 2021-12-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delete',
        ),
    ]
